#!/usr/bin/env ruby

require "dezo"

if ARGV != []
  words = ARGV
  words.each do |word|
    Dezo.search(word)
  end
else
  loop do
    print "word> "
    begin
      word = STDIN.gets.chomp
    rescue Interrupt
      puts "\nBye"
      break
    end

    break if word === "Q"
    next if word ==  ""
    Dezo.search(word)
  end
end
