#!/usr/bin/env ruby

require "dezo"

if ARGV != []
  words = ARGV
  words.each do |word|
    Dezo.search(word)
  end
else
  loop do
    print "word> "
    word = STDIN.gets.chomp
    #word = Word.new

    break if word === "Q"
    next if word ==  ""
    Dezo.search(word)
  end
end
